#178 min values should be gte not gt
rainlanguage/rain.webapp pull request #184
Opened 2024-10-17 08:40 UTC by hardingjam

## Motivation

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-10-18 12:56 UTC, thedavidmeister requested changes

2024-10-18 12:56 UTC, thedavidmeister commented on app/_services/frameState.ts
> +				} else if (inputText && Number(inputText) >= Number(currentDeposit.min)) {
<img width="857" alt="Screenshot 2024-10-18 at 16 55 53" src="https://github.com/user-attachments/assets/d4fdec00-ac7c-414a-9e3c-3a18ca678b43">

check line 49 of this file, it says "greater than"

2024-10-21 15:30 UTC, hardyjosh submitted a review, later dismissed

2024-10-21 15:51 UTC, hardyjosh approved these changes

2024-10-21 15:52 UTC, merged