Fix disclaimer height with breakpoint
rainlanguage/rain.webapp pull request #228
Opened 2024-10-24 16:32 UTC by hardingjam

## Motivation

## Solution

https://github.com/user-attachments/assets/c24de754-f443-4ae6-bccd-0e562466309d

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs
- [ ] included screenshots (if this involves a front-end change)

2024-10-24 17:03 UTC, hardyjosh commented
this doesn't look quite right on desktop anymore

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/825e1e72-9029-4960-acd1-fba2e2f6397b">

2024-10-28 13:37 UTC, hardyjosh requested changes
pls fix this 
<img width="1725" alt="image" src="https://github.com/user-attachments/assets/ae057167-9a39-4fad-8483-8782f14e9f5c">

should look as it did before

2024-10-28 15:23 UTC, hardingjam commented
> should look as it did before

![image](https://github.com/user-attachments/assets/a757aa3f-eef7-44fd-b01e-1d1f81ca08f3)

This is what it looks like on main - is this correct?

2025-03-18 08:32 UTC, hardyjosh commented
closing as this version of the webapp is due to be deprecated

2025-03-18 08:32 UTC, closed without merging