Add basic codemirror modal
rainlanguage/rain.webapp pull request #43
Opened 2024-09-29 21:15 UTC by hardyjosh

## Motivation

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs

2024-09-29 21:16 UTC, hardyjosh commented
fixes #11

2024-10-02 13:15 UTC, hardingjam commented
Fixed the CodeMirror to have a fixed height and be scrollable - looks ready to go

2024-10-08 18:10 UTC, thedavidmeister requested changes
no screenshots or tests

2024-10-10 16:16 UTC, thedavidmeister requested changes
judging by the screenshots, the bindings are not working (io ratio bindings are 0)

2024-10-23 13:40 UTC, thedavidmeister requested changes

2024-10-23 13:40 UTC, thedavidmeister commented on app/_components/CodemirrorModal.tsx
> +	console.log(yamlData);
console log

2024-10-23 13:40 UTC, thedavidmeister commented on app/_components/CodemirrorModal.tsx
> +	console.log('scen', scenario);
console log

2024-10-23 13:40 UTC, thedavidmeister commented on app/_components/CodemirrorModal.tsx
> +		console.log('currentState', currentState.bindings);
console log

2024-10-23 14:46 UTC, thedavidmeister approved these changes

2024-10-23 14:48 UTC, merged