01/10/24 default to text field if only custom button appears
rainlanguage/rain.webapp pull request #70
Opened 2024-10-02 11:23 UTC by hardingjam

## Motivation

Some friction for users where there is a "Custom" button that must be clicked, despite no multi-choice option

## Solution

Closes #27 

If there are no presets on a field, then show the text input directly

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs

2024-10-06 09:28 UTC, thedavidmeister requested changes
no tests or screenshots for this on the PR

2024-10-07 12:46 UTC, hardingjam commented
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/6c5f6fa4-ff29-4d9c-aae6-03ed6086f91c">

2024-10-08 18:15 UTC, thedavidmeister requested changes

2024-10-08 18:15 UTC, thedavidmeister commented on __mocks__/fixed-limit.ts
> +export const mockFixedLimit = `raindex-version: 8898591f3bcaa21dc91dc3b8584330fc405eadfa
why is this mock so large?

is all of this needed to test this test?

2024-10-12 03:19 UTC, thedavidmeister submitted a review, later dismissed

2024-10-12 03:19 UTC, thedavidmeister commented on __tests__/WebappFrame.test.tsx
> +import { mockFixedLimit } from '@/__mocks__/fixed-limit';
fixtures?

2024-10-21 12:15 UTC, hardyjosh commented on app/_components/WebappFrame.tsx
> +		console.log(buttonsData);
console log

2024-10-21 15:26 UTC, hardyjosh approved these changes

2024-10-21 15:28 UTC, merged