02/10/24 button text fall back to value or
rainlanguage/rain.webapp pull request #71
Opened 2024-10-02 11:25 UTC by hardingjam

## Motivation

Button text can be "undefined"

## Solution

Fall back to the value property
If no value exists, then do not show a button
Closes

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs

2024-10-06 09:29 UTC, thedavidmeister requested changes
no tests or screenshots on this PR

2024-10-07 12:57 UTC, hardingjam commented
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/9ecd558f-4c72-48f5-a6f4-a1b072f786c3">

<img width="739" alt="image" src="https://github.com/user-attachments/assets/9bbf33c4-89ea-4d7a-b3f9-220d579ec9e0">

2024-10-08 18:22 UTC, thedavidmeister requested changes

2024-10-08 18:22 UTC, thedavidmeister commented on __mocks__/mockFrameStates.ts
> +export const fieldsFrameState = {
these mocks seem too big for the test

2024-10-10 16:40 UTC, thedavidmeister requested changes
why are we calling fixtures mocks?

2024-10-15 11:26 UTC, thedavidmeister approved these changes

2024-10-15 11:55 UTC, merged