#30 Descriptions don't include linebreaks
rainlanguage/rain.webapp pull request #72
Opened 2024-10-02 13:19 UTC by hardingjam

## Motivation

## Solution

Add tailwind class to include line breaks

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs

2024-10-06 09:30 UTC, thedavidmeister requested changes
no screenshots on this PR

2024-10-06 09:30 UTC, thedavidmeister commented on app/_components/FrameImage.tsx
> +					className="top-0 md:text-xl text-sm border rounded-full bg-gray-100 px-6 py-3 my-4 md:mb-0 "
why add this whitespace?

2024-10-07 10:39 UTC, hardingjam commented
<img width="785" alt="image" src="https://github.com/user-attachments/assets/e8b5d5a7-1ff2-4257-b8cd-11cb97092134">

2024-10-07 12:45 UTC, hardingjam commented
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/29cba245-3d00-4fb0-a66d-9b5d0c233749">

2024-10-08 18:23 UTC, thedavidmeister approved these changes

2024-10-09 06:49 UTC, merged